### PR TITLE
add fastmath for min and max

### PR DESCRIPTION
**Pull request by KristofferC**
Should fix https://github.com/eschnett/SIMD.jl/issues/103

@seelengrab, can you test this?

### CODE REVIEW

**Comment by eschnett** [comment]
This is a somewhat "unreliable" implementation: It implements `min` in terms of other functions (`<`, `vifelse`), and then expects LLVM to find a good translation. A different approach would be to lower `min` to the respective LLVM intrinsic (`fmin`) and then to apply the respective flags (`fastmath` etc.).

**Comment by KristofferC** [comment]
Yes, I was lazy :P. The intrinsic is minnum: https://github.com/eschnett/SIMD.jl/blob/705384c0dffaaaa17e677ec6567584ad433859d0/src/LLVM_intrinsics.jl#L241.

We currently call that as a `ccall` which doesn't support passing any fastmath flags. I can rewrite it to LLVM IR and add the fast math flags and see how it goes.

**Comment by eschnett** [comment]
Don't let the better be the enemy of the good: If it works and if it improves the code, then thank you for your work. You could add a respective comment that what you suggest above is the way to go for the future, and that there is no particular reason to implement fastmath `min` in this way.

**Comment by KristofferC** [comment]
I think this approach should be better:

```llvm
julia> mymin(a, b) = @fastmath min(a, b)
mymin (generic function with 1 method)

julia> v = SIMD.Vec(1.0,2.0,3.0,4.0)
<4 x Float64>[1.0, 2.0, 3.0, 4.0]

julia> @code_llvm mymin(v,v)
;  @ REPL[2]:1 within `mymin`
  %3 = getelementptr inbounds [1 x <4 x double>], [1 x <4 x double>]* %1, i64 0, i64 0
  %4 = getelementptr inbounds [1 x <4 x double>], [1 x <4 x double>]* %2, i64 0, i64 0
  %5 = load <4 x double>, <4 x double>* %3, align 16
  %6 = load <4 x double>, <4 x double>* %4, align 16
  %res.i = call fast <4 x double> @llvm.minnum.v4f64(<4 x double> %5, <4 x double> %6)
  %7 = getelementptr inbounds [1 x <4 x double>], [1 x <4 x double>]* %0, i64 0, i64 0
  store <4 x double> %res.i, <4 x double>* %7, align 32
  ret void
}
```

**Comment by Seelengrab** [comment]
I can confirm that this PR works :+1: Thanks for the quick turnaround! The assembly is now exactly what I'd hope it to be.

**Pull request merged**
