### PR TITLE
CI Updates

### PR DESCRIPTION
**Pull request by sjkelly**
This should fix CI when testing. Also drops 0.7 in exchange for 1.2.

### CODE REVIEW

**Comment by eschnett** [comment]
Is it necessary to drop support for 0.7?
Is it necessary to remove the manifest?

**Comment by sjkelly** [comment]
It is not necessary to drop 0.7, but from what I understand 1.0 is the LTS version, and 0.7 will not receive updates as it was just a transitional release. I'm happy to leave 0.7 and just add 1.2.

From what I understand the Manifest.toml should not be committed for packages because the SAT solver will generate the specifications automatically from the Project.toml. I haven't found an authoritative explanation, but my observation is that it is distributed when you want to specify a certain branch or commit in your application and allow someone to completely replicate your environment.

**Comment by eschnett** [comment]
Where are my manners? Thanks for the update!

If possible, I'd prefer to keep 0.7 in there as long as it works. If it breaks I'll take it out.

Thanks for the explanation regarding the manifest. It seems Julia is using it if it's present, and that doesn't seem useful.

**Comment by sjkelly** [comment]
Thank _you_ for this great package. I've added back 0.7 and made a few adjustments to the .gitignore as well.

**Pull request merged**
