### PR TITLE
Rename ifelse to vifelse

### PR DESCRIPTION
**Pull request by GunnarFarneback**
This attempts to solve #28 by renaming `ifelse` to `vifelse`, as an alternative to #29.

### CODE REVIEW

**Comment by GunnarFarneback** [comment]
I can reproduce the Travis crash locally, most of the time; it doesn't happen every time. Also it happens less frequently when doing `using SIMD` followed by including `runtests.jl` than when doing `] test SIMD`. I'm lost on how to track it down though. Any suggestions?

**Comment by GunnarFarneback** [comment]
After updating Julia to latest master I can't reproduce this crash anymore.

**Comment by eschnett** [comment]
Given the symptoms, I assume (was assuming) a code generation problem that might be due to a bug in LLVM (there are quite a few of these with SIMD code), in Julia, and/or in SIMD.jl.

The problem with Julia is that it uses a different calling convention that C/C++ for SIMD values, and thus uses different code paths in LLVM where bugs exist that are not tested by other languages. At least that was the case a few years ago -- I have not checked recently. (Julia passes SIMD vectors by reference, like any other tuple, while C passes them either in vector registers or on the stack. The respective code to load/save/spill variables then has problems when many different vector sizes are legal (e.g. AVX) and when the SIMD vector size is not a multiple of the "natural" vector size.)

I will look at the pull requests later this week and pull one. @GunnarFarneback if you have a preference, let me know.

**Comment by eschnett** [comment]
I found the reason for the segfaults: When calling `valloc`, I assume it is safe to read "a bit" further than the allocated size (up to the next complete vector length). The `valloc` implementation did not guarantee this, though. Given current hardware, I think this should have worked anyway, but I modified `valloc` to add sufficient extra padding, which is cleaner anyway.

I will soon push my branch.

**Comment by eschnett** [comment]
I have pushed my branch, which should be a superset of this branch.

**Comment by GunnarFarneback** [comment]
Great to know those segfaults have been solved.

**Pull request closed without merging**
